// RecordFinder+Registry.swift
// GH #230 — the Record Finder's DATA: one `Site` per archive. Split from
// RecordFinder.swift (the template language and evaluator) so adding an
// archive is an edit to this table and nothing else. Sources:
// docs/research/irish_records_design_2026-09-30.md §2/§4 (re-checked 2026-10-01) and
// docs/research/uk_scotland_records_survey_2026-10-01.md §5. Every URL shape here is
// pinned by RecordFinderLinkTests.
//
// C++ readers: an `extension` adds members to a type declared elsewhere —
// like defining more static members of a class in a second .cpp file.

import Foundation

extension RecordFinder {

    // MARK: - The registry

    /// Every site, in the order the menu shows them.
    public static var all: [Site] { ireland + military + britain + burials }

    /// Burials and memorials, worldwide.
    ///
    /// Find a Grave WAS an automated Research Person source; its robots.txt
    /// has disallowed /memorial/search since 2024-11-25, so on 2026-10-01
    /// (Rick approved; survey §6.1) it became this link. A person clicking a
    /// link in their own browser is not a crawler; the app fetching it was.
    public static let burials: [Site] = [
        Site(id: "world.findagrave",
             title: "Find a Grave — memorial search",
             group: "Burials and memorials",
             reason: "Recorded in {place}: volunteer memorials, often with a headstone photo and family links.",
             searchURL: "https://www.findagrave.com/memorial/search",
             parameters: [
                Parameter("firstname", .givenName),
                Parameter("lastname", .surname, required: true),
                Parameter("birthyear", .birthYear),
                Parameter("birthyearfilter", .constant("5")),
                Parameter("deathyear", .deathYearOffset(0)),
                Parameter("deathyearfilter", .constant("5")),
             ],
             formURL: "https://www.findagrave.com/",
             conditions: [.any([.recordedIn(.unitedStates), .recordedIn(.ireland), .recordedIn(.england),
                                .recordedIn(.wales), .recordedIn(.scotland)])],
             verification: .verified("survey 2026-10-01: search 200 with 21 memorial links; parameter names as the old adapter used them")),
    ]

    // Region shorthands for the tables below.
    private typealias R = FamilyTreeResearchLinks.Region
    private static let inGB: Condition = .any([.recordedIn(.england), .recordedIn(.wales), .recordedIn(.scotland)])
    private static let inEW: Condition = .any([.recordedIn(.england), .recordedIn(.wales)])
    private static let bornEW: Condition = .any([.bornIn(.england), .bornIn(.wales)])
    private static let diedEW: Condition = .any([.diedIn(.england), .diedIn(.wales)])
    private static let diedGB: Condition = .any([.diedIn(.england), .diedIn(.wales), .diedIn(.scotland)])

    /// Ireland — docs/research/irish_records_design_2026-09-30.md §2/§4, URL shapes
    /// re-checked 2026-10-01.
    public static let ireland: [Site] = [
        Site(id: "ie.nai.census-1901-1911",
             title: "Census of Ireland 1901 / 1911",
             group: "Ireland",
             reason: "Recorded in {place}. The only two surviving full censuses — household returns, occupations and townland, free, with scans of the original forms.",
             searchURL: "https://nationalarchives.ie/collections/search-the-census/search-results/",
             parameters: [
                Parameter("census_year", .singleYearAlive([1901, 1911])),
                Parameter("surname", .surname, required: true),
                Parameter("firstname", .givenName),
                Parameter("county", .irishCensusCounty),
             ],
             formURL: "https://nationalarchives.ie/collections/search-the-census/",
             conditions: [.recordedIn(.ireland), .any([.aliveIn(1901), .aliveIn(1911)])],
             verification: .verified("2026-10-01: results page 200; the same parameters on api-census.nationalarchives.ie return the rows (county spelled as the index spells it, e.g. \"King's Co.\")")),
        Site(id: "ie.nai.census-1926",
             title: "Census of Ireland 1926",
             group: "Ireland",
             reason: "Released April 2026 — every household in the Irish Free State on 18 April 1926. Opens the search form.",
             searchURL: nil,
             formURL: "https://nationalarchives.ie/collections/search-the-1926-census/",
             conditions: [.recordedIn(.ireland), .aliveIn(1926), .not(.northernIrishCounty)],
             verification: .formOnly("2026-10-01: form page 200; its query parameters are not yet pinned")),
        Site(id: "ie.nai.census-1821-1851",
             title: "Census fragments 1821–1851",
             group: "Ireland",
             reason: "What survived the 1922 fire of the earlier censuses — patchy, but whole parishes in a few counties. Opens the search form.",
             searchURL: nil,
             formURL: "https://nationalarchives.ie/collections/search-the-census-c19/",
             conditions: [.recordedIn(.ireland), .bornBefore(1851)],
             verification: .formOnly("2026-10-01: form page 200")),
        Site(id: "ie.irishgenealogy.civil-church",
             title: "Irish civil records and church registers (irishgenealogy.ie)",
             group: "Ireland",
             reason: "State registration with register images — births 1864–1924, marriages 1845–1949, deaths 1871–1974 — plus Catholic registers for Cork and Ross, Dublin, Kerry and Carlow. Download the PDF and use I found a record… to file it.",
             searchURL: "https://www.irishgenealogy.ie/search/",
             parameters: [
                Parameter("church-or-civil", .constant("all")),
                Parameter("firstname", .givenName),
                Parameter("lastname", .surname, required: true),
                Parameter("location", .irishCounty),
                Parameter("yearStart", .lifeStart(-1)),
                Parameter("yearEnd", .lifeEnd(1)),
                Parameter("event-birth", .constant("1")),
                Parameter("event-marriage", .constant("1")),
                Parameter("event-death", .constant("1")),
                Parameter("event-baptism", .constant("1")),
                Parameter("event-burial", .constant("1")),
             ],
             formURL: "https://www.irishgenealogy.ie/search/",
             conditions: [.recordedIn(.ireland)],
             verification: .browserOnly("2026-10-01: field names read from real result pages captured by the Wayback Machine on 2026-04-06 and 2026-09-05 (20 record links rendered); the live site answers scripts with a Cloudflare challenge")),
        Site(id: "ie.griffiths",
             title: "Griffith's Valuation 1847–1864 (askaboutireland.ie)",
             group: "Ireland",
             reason: "Who held land and houses in {place} in the 1850s — the bridge that places a surname in a townland before civil registration.",
             searchURL: "https://www.askaboutireland.ie/griffith-valuation/index.xml",
             parameters: [
                Parameter("action", .constant("doNameSearch")),
                Parameter("familyname", .surname, required: true),
                Parameter("firstname", .givenNameIfBornBefore(1845)),
                Parameter("countyname", .irishCounty),
             ],
             formURL: "https://www.askaboutireland.ie/griffith-valuation/",
             conditions: [.recordedIn(.ireland), .bornBefore(1920)],
             verification: .browserOnly("Wayback captures 2023–2024 of real name searches; live site challenges scripts")),
        Site(id: "ie.nli.registers",
             title: "Catholic parish registers — page images (NLI)",
             group: "Ireland",
             reason: "Page images of the Catholic registers, mostly to 1880, searchable by parish — no name index. Find the entry in the FindMyPast index below, then open the page here.",
             searchURL: "https://registers.nli.ie/",
             parameters: [Parameter("q", .firstOf([.irishTown, .irishCounty]), required: true)],
             formURL: "https://registers.nli.ie/",
             conditions: [.recordedIn(.ireland), .bornBefore(1900)],
             verification: .browserOnly("q= seen on real captured URLs; live site challenges scripts")),
        Site(id: "ie.findmypast.catholic-baptisms",
             title: "Irish Catholic baptisms index (FindMyPast, free account)",
             group: "Ireland",
             reason: "The free name index to the NLI registers — child, parents, parish and date — so you know which register page to open.",
             searchURL: "https://www.findmypast.ie/search/results",
             parameters: [
                Parameter("datasetname", .constant("ireland roman catholic parish baptisms")),
                Parameter("firstname", .givenName),
                Parameter("lastname", .surname, required: true),
                Parameter("yearofbirth", .birthYear),
                Parameter("yearofbirth_offset", .constant("2")),
             ],
             formURL: "https://www.findmypast.ie/search/ireland",
             conditions: [.recordedIn(.ireland), .bornBefore(1915)],
             verification: .browserOnly("datasetname/lastname/firstname from captured real URLs (2023–2025); scripts get 403")),
        Site(id: "ie.proni.wills",
             title: "PRONI will calendars (Northern Ireland)",
             group: "Ireland",
             reason: "{place} is in Northern Ireland: will calendars 1858–1965 with images. Opens the search form (it cannot be pre-filled).",
             searchURL: nil,
             formURL: "https://apps.proni.gov.uk/WillsCalendar_IE/WillsSearch.aspx",
             conditions: [.northernIrishCounty, .diedFrom(1858)],
             verification: .formOnly("2026-10-01: 200; ASP.NET postback form")),
        Site(id: "ie.nai.genealogy",
             title: "National Archives genealogy (tithe, wills)",
             group: "Ireland",
             reason: "Tithe Applotment Books 1823–37, Calendars of Wills 1858–1920, soldiers' wills. Opens the search form.",
             searchURL: nil,
             formURL: "https://genealogy.nationalarchives.ie/",
             conditions: [.recordedIn(.ireland)],
             verification: .formOnly("Cloudflare to scripts; form landing page")),
    ]

    /// UK military service (Irish soldiers served in the British Army). The
    /// automated Discovery adapter (app side) fetches the references; these
    /// are the same searches for the browser.
    public static let military: [Site] = [
        Site(id: "uk.tna.wo97",
             title: "British Army service records to 1913 (TNA Discovery, WO 97)",
             group: "Military records (UK)",
             reason: "The tree records military service. Soldiers' documents for men discharged to pension — birthplace, regiment, next of kin. The catalogue entry is free; the image is on FindMyPast/Ancestry.",
             searchURL: "https://discovery.nationalarchives.gov.uk/results/r",
             parameters: [Parameter("_q", .surnameThenGiven, required: true),
                          Parameter("_ser", .constant("WO 97"))],
             formURL: "https://discovery.nationalarchives.gov.uk/",
             conditions: [.servedInMilitary, .bornBefore(1898)],
             verification: .verified("2026-10-01: API equivalent returns WO 97 rows; _q/_ser on captured result pages")),
        Site(id: "uk.tna.wo363",
             title: "British Army WWI service records (TNA Discovery, WO 363)",
             group: "Military records (UK)",
             reason: "The tree records military service. The surviving First World War service records (about 40% survived the 1940 bombing).",
             searchURL: "https://discovery.nationalarchives.gov.uk/results/r",
             parameters: [Parameter("_q", .surnameThenGiven, required: true),
                          Parameter("_ser", .constant("WO 363"))],
             formURL: "https://discovery.nationalarchives.gov.uk/",
             conditions: [.servedInMilitary, .aliveIn(1914), .bornBefore(1902)],
             verification: .verified("2026-10-01: API equivalent returns WO 363 rows")),
    ]

    /// England, Wales and Scotland — docs/research/uk_scotland_records_survey_2026-10-01.md §5.
    public static let britain: [Site] = {
        func fs(_ id: String, _ title: String, _ collection: String, _ reason: String,
                countries: [R], conditions: [Condition], group: String) -> Site {
            Site(id: id, title: title, group: group, reason: reason,
                 searchURL: "https://www.familysearch.org/search/record/results",
                 parameters: [
                    Parameter("q.givenName", .givenName),
                    Parameter("q.surname", .surname, required: true),
                    Parameter("q.birthLikeDate.from", .birthYearOffset(-5)),
                    Parameter("q.birthLikeDate.to", .birthYearOffset(5)),
                    Parameter("q.birthLikePlace", .birthCountry(countries)),
                    Parameter("f.collectionId", .constant(collection)),
                 ],
                 formURL: "https://www.familysearch.org/search/record/results",
                 conditions: conditions,
                 verification: .browserOnly("collection id confirmed via its collection page (survey 2026-10-01); FamilySearch 403s scripts"))
        }
        let ew = "England and Wales"
        let sct = "Scotland"
        return [
            fs("gb.fs.ew-birth-index", "FamilySearch — England and Wales birth index 1837–2008", "2285338",
               "Born in {place}: the GRO quarterly birth index, with mother's maiden name from 1911.",
               countries: [.england, .wales], conditions: [bornEW, .bornFrom(1837)], group: ew),
            fs("gb.fs.england-births", "FamilySearch — England births and christenings 1538–1975", "1473014",
               "Born in {place}: parish baptisms, often with both parents' names.",
               countries: [.england], conditions: [.bornIn(.england), .bornBefore(1900)], group: ew),
            fs("gb.fs.ew-marriage-index", "FamilySearch — England and Wales marriage index 1837–2005", "2285732",
               "Recorded in {place}: the GRO quarterly marriage index.",
               countries: [.england, .wales], conditions: [inEW, .bornFrom(1815)], group: ew),
            fs("gb.fs.ew-death-index", "FamilySearch — England and Wales death index 1837–2007", "2285341",
               "Died in {place}: the GRO quarterly death index, with age at death.",
               countries: [.england, .wales], conditions: [diedEW, .diedFrom(1837)], group: ew),
            fs("gb.fs.england-burials", "FamilySearch — England deaths and burials 1538–1991", "1473016",
               "Died in {place}: parish burials.",
               countries: [.england], conditions: [.diedIn(.england), .diedBefore(1900)], group: ew),
            fs("gb.fs.ew-census-1881", "FamilySearch — England and Wales census 1881", "2562194",
               "Recorded in {place} and alive in 1881: the fully indexed census.",
               countries: [.england, .wales], conditions: [inEW, .aliveIn(1881)], group: ew),
            fs("gb.fs.ew-census-1911", "FamilySearch — England and Wales census 1911", "1921547",
               "Recorded in {place} and alive in 1911.",
               countries: [.england, .wales], conditions: [inEW, .aliveIn(1911)], group: ew),
            fs("gb.fs.scotland-births", "FamilySearch — Scotland births and baptisms 1564–1950", "1771030",
               "Recorded in {place}: Old Parish Register baptisms and later births.",
               countries: [.scotland], conditions: [.recordedIn(.scotland), .bornBefore(1950)], group: sct),
            fs("gb.fs.scotland-marriages", "FamilySearch — Scotland marriages 1561–1910", "1771074",
               "Recorded in {place}: Old Parish Register banns and marriages.",
               countries: [.scotland], conditions: [.recordedIn(.scotland), .bornBefore(1895)], group: sct),
            Site(id: "gb.findmypast",
                 title: "FindMyPast (UK) — census, parish registers, 1921 census",
                 group: ew,
                 reason: "Recorded in {place}. Index search is free; the 1921 census is only here.",
                 searchURL: "https://www.findmypast.co.uk/search/results",
                 parameters: [
                    Parameter("firstname", .givenName),
                    Parameter("lastname", .surname, required: true),
                    Parameter("yearofbirth", .birthYear),
                    Parameter("yearofbirth_offset", .constant("5")),
                 ],
                 formURL: "https://www.findmypast.co.uk/search",
                 conditions: [inGB],
                 verification: .verified("survey 2026-10-01: firstname/lastname 200; yearofbirth from the Irish site's captured URLs")),
            Site(id: "gb.tna.discovery",
                 title: "The National Archives (UK) Discovery",
                 group: ew,
                 reason: "Recorded in {place}: the national catalogue — wills before 1858 (PROB 11), service records, court and estate papers.",
                 searchURL: "https://discovery.nationalarchives.gov.uk/results/r",
                 parameters: [Parameter("_q", .surnameThenGiven, required: true)],
                 formURL: "https://discovery.nationalarchives.gov.uk/",
                 conditions: [inEW],
                 verification: .verified("survey 2026-10-01")),
            Site(id: "gb.genuki.england",
                 title: "GENUKI — where the county's records are kept",
                 group: ew,
                 reason: "Recorded in {place}: the county page lists every parish's registers, census and memorial sets and where they are held.",
                 searchURL: "https://www.genuki.org.uk/big/eng/",
                 pathField: .englishChapman,
                 formURL: "https://www.genuki.org.uk/big/eng",
                 conditions: [.recordedIn(.england)],
                 verification: .verified("survey 2026-10-01: /big/eng/CON 200")),
            Site(id: "gb.genuki.wales",
                 title: "GENUKI — Wales",
                 group: ew,
                 reason: "Recorded in {place}: where the Welsh parish registers and census returns are held.",
                 searchURL: nil,
                 formURL: "https://www.genuki.org.uk/big/wal",
                 conditions: [.recordedIn(.wales)],
                 verification: .formOnly("country page")),
            Site(id: "gb.genuki.scotland",
                 title: "GENUKI — Scotland",
                 group: sct,
                 reason: "Recorded in {place}: where each Scottish parish's records are held.",
                 searchURL: nil,
                 formURL: "https://www.genuki.org.uk/big/sct",
                 conditions: [.recordedIn(.scotland)],
                 verification: .formOnly("country page")),
            Site(id: "gb.deceasedonline",
                 title: "Deceased Online — council burial registers",
                 group: ew,
                 reason: "Died in {place}: burial and cremation registers of participating councils (pay per view).",
                 searchURL: "https://www.deceasedonline.com/dec_search.php",
                 parameters: [
                    Parameter("s", .surname, required: true),
                    Parameter("f", .givenName),
                    Parameter("b", .deathYearOffset(-1)),
                    Parameter("e", .deathYearOffset(2)),
                 ],
                 formURL: "https://www.deceasedonline.com/",
                 conditions: [diedGB],
                 verification: .browserOnly("GET form field names read from the home page (survey); pre-fill not yet clicked through")),
            Site(id: "gb.billiongraves",
                 title: "BillionGraves — headstone photos (UK)",
                 group: ew,
                 reason: "Died in {place}: GPS-tagged headstone photos and transcriptions.",
                 searchURL: "https://billiongraves.com/search/results",
                 parameters: [
                    Parameter("given_names", .givenName),
                    Parameter("family_names", .surname, required: true),
                    Parameter("country", .constant("United Kingdom")),
                 ],
                 formURL: "https://billiongraves.com/",
                 conditions: [diedGB],
                 verification: .browserOnly("200 to scripts but a JS app; results only render in a browser")),
            // Tier 4 — blank forms. Their terms allow only a person typing
            // into the search ("The use of front end programs or sites to
            // enter search parameters is strictly forbidden" — FreeBMD), or
            // a login comes first. The link opens the form; nothing more.
            Site(id: "gb.freebmd",
                 title: "FreeBMD — England and Wales BMD index (type the search yourself)",
                 group: ew,
                 reason: "Recorded in {place}. Free volunteer index to GRO births, marriages and deaths from 1837; their terms allow only searches typed by hand.",
                 searchURL: nil,
                 formURL: "https://www.freebmd.org.uk/cgi/search.pl",
                 conditions: [inEW, .diedFrom(1837)],
                 verification: .formOnly("POST + terms forbid software filling in the search")),
            Site(id: "gb.freecen",
                 title: "FreeCEN — census transcriptions 1841–1901 (type the search yourself)",
                 group: ew,
                 reason: "Recorded in {place}. Free census transcriptions, strongest for Scotland 1841/1851; searches by hand only.",
                 searchURL: nil,
                 formURL: "https://www.freecen.org.uk/search_queries/new",
                 conditions: [inGB, .diedFrom(1841), .bornBefore(1911)],
                 verification: .formOnly("POST + CSRF; terms forbid software filling in the search")),
            Site(id: "gb.freereg",
                 title: "FreeREG — parish register transcriptions (type the search yourself)",
                 group: ew,
                 reason: "Recorded in {place}. Free baptism, marriage and burial transcriptions from 1538; searches by hand only.",
                 searchURL: nil,
                 formURL: "https://www.freereg.org.uk/search_queries/new",
                 conditions: [inGB, .bornBefore(1900)],
                 verification: .formOnly("POST + CSRF")),
            Site(id: "gb.gro",
                 title: "GRO England and Wales index (login)",
                 group: ew,
                 reason: "Recorded in {place}. The official index — births with mother's maiden name, deaths with age; certificate PDFs to order. Log in, then search.",
                 searchURL: nil,
                 formURL: "https://www.gro.gov.uk/gro/content/certificates/indexes_search.asp",
                 conditions: [inEW, .diedFrom(1837)],
                 verification: .formOnly("302 to Login.asp")),
            Site(id: "gb.probate",
                 title: "Probate calendar — England and Wales wills from 1858",
                 group: ew,
                 reason: "Died in {place}: the national calendar of wills and administrations; copies to order.",
                 searchURL: nil,
                 formURL: "https://www.gov.uk/search-will-probate",
                 conditions: [diedEW, .diedFrom(1858)],
                 verification: .formOnly("gov.uk landing page")),
            Site(id: "gb.scotlandspeople.births",
                 title: "ScotlandsPeople — statutory births (login)",
                 group: sct,
                 reason: "Recorded in {place}. Scottish birth entries from 1855 name the parents' marriage date and place. Log in, then search.",
                 searchURL: nil,
                 formURL: "https://www.scotlandspeople.gov.uk/search-records/statutory-records/stat_births",
                 conditions: [.recordedIn(.scotland), .bornFrom(1855)],
                 verification: .formOnly("login; terms forbid automated access")),
            Site(id: "gb.scotlandspeople.baptisms",
                 title: "ScotlandsPeople — church baptisms (login)",
                 group: sct,
                 reason: "Recorded in {place}. Old Parish Register baptisms before 1855. Log in, then search.",
                 searchURL: nil,
                 formURL: "https://www.scotlandspeople.gov.uk/search-records/church-registers/church-births-baptisms",
                 conditions: [.recordedIn(.scotland), .bornBefore(1855)],
                 verification: .formOnly("login; terms forbid automated access")),
        ]
    }()
}
