// Tagging.swift
// Caption and user-confirmed person-tag value types — moved verbatim from
// Models.swift (refactor 2026-06-26, model decomposition step 1), then into
// the VideoScanCore package (2026-06-26 step 3). `public` added during
// package extraction: app code (CaptionRunner, InspectorFamilyTagsView,
// ConfirmPersonSheet) constructs and reads these across the module boundary.

import Foundation

// MARK: - Scene Caption

/// One vision-language model caption pinned to a specific frame of a
/// video. Sibling annotation to `detectedPeople` — captions describe
/// what's happening ("a man playing guitar in a kitchen") without
/// claiming identity. Together with face tags, makes the catalog
/// searchable in natural language ("Donna playing guitar" → match
/// on detectedPeople ∪ sceneCaptions text).
///
/// See docs/scene_captions_plan.md for the long-arc design.
public struct SceneCaption: Codable, Hashable, Sendable {
    /// Seconds into the clip the caption describes.
    public let timestamp: Double
    /// The caption text as generated by the VLM.
    public let text: String

    // Public memberwise init: app code (CaptionRunner) builds SceneCaptions
    // across the module boundary.
    public init(timestamp: Double, text: String) {
        self.timestamp = timestamp
        self.text = text
    }
}

/// A user-confirmed person tag. Distinct from `detectedPeople` (which
/// is whatever the face-recognition engine produced); this is "Rick
/// said yes, that IS Donna." Provenance (`confirmedAt`) lets the UI
/// show "tagged 2026-04-12" later and feeds the eventual classifier-
/// training loop with ground-truth examples.
public struct ConfirmedTag: Codable, Hashable, Sendable, Identifiable {
    /// Person name. Should match a POI in the gallery when possible
    /// so that "Donna" from manual tagging joins up with "Donna" from
    /// detected matches under one display label.
    public let name: String
    /// When Rick clicked "this is Donna" on this record. Wall-clock,
    /// not media time.
    public let confirmedAt: Date

    // Public memberwise init: app code (InspectorFamilyTagsView,
    // ConfirmPersonSheet) builds ConfirmedTags across the module boundary.
    public init(name: String, confirmedAt: Date) {
        self.name = name
        self.confirmedAt = confirmedAt
    }

    public var id: String { "\(name)@\(confirmedAt.timeIntervalSince1970)" }
}
